# This is a basic workflow to help you get started with Actions
permissions:
  write-all
  
name: helm_chart_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - vsphere

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Config Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: v3.5.4

      - name: run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17

      - name: generate html
        run: |
          go install github.com/halkeye/helm-repo-html@v0.0.8
          /home/runner/go/bin/helm-repo-html

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update index.html"
